import { test, expect } from '@playwright/test';

test('test generated by codegen', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.getByRole('link', { name: 'Docs' }).click();
  await expect(page.getByRole('button', { name: 'Switch between dark and light' })).toBeVisible();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'GitHub repository' }).click();
  const page1 = await page1Promise;
  await page.waitForTimeout(3000);
  await page1.close();
  await page.getByRole('button', { name: 'Search (Control+k)' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).click();
  await page.getByRole('searchbox', { name: 'Search' }).fill('auto-wait');
  await page.waitForTimeout(3000);
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.waitForTimeout(3000);
});